ximion/appstream-generator

source/archive.d
source/backends/debian/tagfile.d
source/bindings/libarchive.d

This reverts some of 63584a0 and fixes #1 
See [libarchive #706](https://github.com/libarchive/libarchive/issues/706#issuecomment-219239144) for an explanation of why this is necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ximion/appstream-generator/8)

Handle compressed empty files correctly

---

source/datacache.d

`MDB_DUPSORT` should be used when the database is opened.
Using it with `mdb_put` causes an "Invalid argument" error and therefore a crash in the generator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ximion/appstream-generator/10)

Fix incorrect use of LMDB flags

---

contrib/setup/build_js.sh

in particular I am running the generator inside linux containers as
in-container root, so bower refusing to bow on account of being run as root
is kind of silly

run bower with allow root to be able to make js as root

---

source/backends/debian/debpkg.d
source/backends/debian/debpkgindex.d
source/backends/debian/utils.d
source/utils.d

I tried not to break local mirror support, but I haven't actually tested that I didn't...

debian: Support downloading from a mirror in addition to having it locally

---

source/backends/debian/debpkgindex.d

In this case
main/i18n/Translation-foo
contrib/i18n/Translation-bar
we were attempting to open main/i18n/Translation-bar, which doesn't
exist. This was causing a code path to short circuit the function to
load translations, meaning that some were missed.
Fix that to 'continue' instead of return. Also only return translations
in the suite we are asking about, not all translations.

Only retrieve DDTP translations from the section we're looking at

---

source/backends/debian/debpkgindex.d
source/utils.d

I was using `make fast`, and noticed that `getFileContents` wasn't working. I suspect that at higher optimisation levels the `scope (exit) fclose (f)` is happening earlier. It needs to happen before we read from the pointer (see the full commit message).
(Also squash some overly verbose debug logging, which isn't really related to this bug, but here we are.)

Download file to memory fix

---

source/backends/debian/debpkg.d
source/backends/debian/debpkgindex.d
source/utils.d

Two things
- We should catch more than just timeout errors
- There's some thread unsafety when multiple threads try to download the same file - we need to synchronise this.
I'm not sure if the package index is actually accessed by multiple threads - is this bit needed?

Make downloading more robust

---

src/asgen/utils.d

DMD doesn't provide core.sys.linux.stdio, use core.sys.posix.stdio which is provided by all 3 compilers.

Fix build with DMD

---

src/asgen/engine.d

I'm trying a configuration with `xenial-updates` (etc) but not `xenial` and was like "why is it processing all of xenial every time?"
Turns out that, because I run clean each time, it was cleaning all of `xenial` :(. I think that clean should keep base suites around too.

engine: Don't clean packages in base suites

---

src/asgen/utils.d

You know what this is about. :)

download: If we have a last-modified date, set the mtime of the target file

---

data/asgen-hints.json

I was just diffing the `Components` between as-dep11 and asgen, and there are actually quite a few of these. I think we should at least explain the problem in the output.
If it's possible to only output this on Debian & Ubuntu then we should do that, but I don't think it is so it's okay to have it for everyone IMO.
Feel free to edit the message.

hints: icon-not-found: Explain the symlink problem for Debian & Ubuntu

---

README.md

Add `libmustache-d` to README dependencies

trivial: update dependencies

---

src/asgen/zarchive.d

std.file doesn't include std.path in recent phobos. Fixes build with LDC 1.2

Import buildPath directly from std.path

---

docs/asgen-config.md
src/asgen/backends/debian/debpkg.d
src/asgen/backends/debian/debpkgindex.d
src/asgen/backends/interfaces.d
src/asgen/config.d
src/asgen/engine.d
src/asgen/extractor.d

OK, here we go.
See https://bugzilla.gnome.org/show_bug.cgi?id=782795
The GStreamer codec listings in GS look quite bad currently, because there's no AS metadata for them. Upstream didn't want to consider this yet (AFAIK). `type=codec` isn't specced properly in AS and we'd want to fix that before proposing anything up there. Fedora ships downstream metadata in their packages. For us in Debian and Ubuntu we have the ability to generate this information because our package indices specify what's in them (`Gstreamer-*`).
I'll add some questions inline, but I hope the general idea is OK. To test: remove all the `gstreamer1.0-plugins-*` and `gstreamer1.0-libav` packages from your system, open an audio file in totem, launch GS when you're prompted to, and look at the list of packages offered up …

Generate type=codec metadata for gstreamer packages

---

src/asgen/zarchive.d

isFile is only useful to distinguish between files and folders, and will throw an exception if the file doesn't exist. In 0.6.6 it always aborts with an exception unless the archive is already present.

use file.exists to check file existance

---

src/asgen/engine.d

Load the "core" and "extra" components, which contain most of the icon data on Arch Linux.
See also the downstream report:
https://bugs.archlinux.org/task/61157

Load components for Arch Linux

---

src/asgen/backends/alpinelinux/apkpkg.d
src/asgen/backends/alpinelinux/apkpkgindex.d
src/asgen/backends/alpinelinux/package.d
src/asgen/config.d
src/asgen/engine.d
src/asgen/meson.build

alpine: add backend

---

src/asgen/backends/alpinelinux/apkindexutils.d
src/asgen/backends/alpinelinux/apkpkg.d
src/asgen/backends/alpinelinux/apkpkgindex.d
src/asgen/meson.build

I hope I don't have too many style errors this time, the style is still a bit foreign to me :)

alpine: add capabilities to download packages via HTTP

---

src/app.d
src/asgen/config.d

This is useful for e.g. exporting to a versioned
(by date) dir.
fixes #81

config: allow overriding export dir via --exportDir

---

contrib/girwrap/APILookupGdkPixbuf.txt

Gir-to-d tries to handle the return value of 'gdk_pixdata_from_pixbuf' as if it is zero-terminated.
Which causes it to try to use 'getArrayLength' on a void*, causing a compilation error.
Temporary fix for now is to just not export that function.
Additionally, Add missing include for 'FILE*' that GdkPixbufModule needs
inside 'girepo/gdkpixbuf/c/types.d'.

Fix compilation due to broken generated GdkPixbuf code

---

src/asgen/config.d

Currently we tell AsCompose to use optipng just based on the value of
the feature flag. AsCompose will respect what we tell it without further
checking. If optipng is in fact not available then we'll crash later on
when we first try to use it.
Fix this by setting the flag *after* we check if optipng is installed.

config: Move setUseOptipng call after we determine if optipng is available

---

src/asgen/extractor.d

Otherwise it processed twice, and overrides data from metainfo file.
Fixes #88

Also remove the handled desktop file with a suffix

---

.github/workflows/build-test.yml
tests/ci/Dockerfile-fedora-rawhide
tests/ci/install-deps-rpm.sh

As Fedora ships updated D language and GNOME components often earlier
than anyone else, it makes sense to test this to ensure that this
continues to work.

ci: Add Fedora to the CI environment

---

tests/ci/install-deps-rpm.sh

Since Fedora Linux 36, there is now an ffmpeg implementation provided in the main repositories, so let's use it.

Add FFmpeg back to Fedora CI

---

src/asgen/utils.d

Fixes the following stack trace:
2023-04-23 21:02:16 - INFO: Exporting data for v3.15 (main/aarch64) 2023-04-23 21:02:16std.file.FileException@/usr/include/d/std/file.d(2972): /home/abuild/cache/export/media/v3.15/g/gv/gvim.desktop/4016a69fc2135fa29a3414b2c8bd20d9//icons: File exists ----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x563624998170] ??:? @safe void std.file.mkdir!(immutable(char)[]).mkdir(immutable(char)[]) [0x563624a439d0] ??:? @trusted void asgen.utils.copyDir(in immutable(char)[], in immutable(char)[], bool) [0x563624a43500] ??:? /usr/bin/appstream-generator [0x5636249e2190] ??:? void std.parallelism.ParallelForeach!(asgen.backends.interfaces.Package[]).ParallelForeach.opApply(s …

utils: guard mkdir call with std.file.exists

---

README.md

libfreetype6-dev is a deprecated (long time ago) transitional package. Use proper one instead.
Add appstream compose header files.
Add yarnpkg, as otherwise default build instructions will not work.

Update README.md with new dependencies

---

snapcraft.yaml

We should use the one shipped by the gnome snap; us including ours results in breakages such as symbol lookup errors due to mismatched glib versions.
/cc @kenvandine for review

snap: Don't include our glib (#131)

---

data/templates/default/section_page.html

For large repositories this can make the plot more useful at a glance for seeing what has changed between runs.
This will also work without any changes needed when the 'jquery-flot' module gets upgraded to 'flot'.

data: Add tooltip hover for plot graph in section_pages.html

---

src/asgen/iconhandler.d

Most of the non-symbolic icons were moved from Adwaita to AdwaitaLegacy, but some legacy applications still use them.
References:
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/288
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme-legacy

Add AdwaitaLegacy to themeNames
